"""Add job tracking fields to ml_models

Revision ID: f59ecb5874fa
Revises: 64f9ead2f15f
Create Date: 2026-08-09 06:31:13.931078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59ecb5874fa'
down_revision = '64f9ead2f15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_scores_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('explanation_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('training_time_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('training_run_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_ml_models_training_run_id'), ['training_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_training_run_id'))
        batch_op.drop_column('training_run_id')
        batch_op.drop_column('training_time_seconds')
        batch_op.drop_column('error_message')
        batch_op.drop_column('status')
        batch_op.drop_column('explanation_text')
        batch_op.drop_column('cv_scores_json')

    # ### end Alembic commands ###
