"""
The controlled execution layer for the AI Data Analyst (spec sections 9 &
24): the AI is only ever allowed to request one of a small, fixed set of
operations against a *validated* column name. It never gets to submit
Pandas code, a query string, or anything else that would be evaluated.

Flow: AI proposes a plan (JSON) -> validate_plan() checks the operation is
whitelisted and every referenced column actually exists in this dataset ->
execute_plan() runs the corresponding pre-written Pandas routine and
returns real computed numbers. If validation fails, we never execute
anything — we surface a clear error instead of guessing what the AI meant.
"""

import pandas as pd

from app.services.analytics.chart_builder import AGGREGATIONS, apply_filters, ChartBuildError

MAX_RESULT_ROWS = 25
MAX_TREND_POINTS = 36

ALLOWED_OPERATIONS = {
    "none",  # question doesn't need computation (conceptual/general)
    "describe_column",
    "aggregate",
    "top_n",
    "count_rows",
    "correlation",
    "trend",
    "unique_values",
}

TREND_FREQUENCIES = {"D": "D", "W": "W", "M": "ME", "Y": "YE"}


class QueryPlanError(Exception):
    pass


def validate_plan(plan: dict, df: pd.DataFrame) -> None:
    if not isinstance(plan, dict):
        raise QueryPlanError("Plan must be a JSON object.")

    operation = plan.get("operation")
    if operation not in ALLOWED_OPERATIONS:
        raise QueryPlanError(f"Unknown or unsupported operation: {operation!r}")

    if operation == "none":
        return

    columns = df.columns

    def _check_column(field_name):
        value = plan.get(field_name)
        if value is not None and value not in columns:
            raise QueryPlanError(f"Column '{value}' does not exist in this dataset.")

    if operation == "describe_column":
        if not plan.get("column"):
            raise QueryPlanError("describe_column requires a 'column'.")
        _check_column("column")

    elif operation == "aggregate":
        if not plan.get("column") or not plan.get("agg"):
            raise QueryPlanError("aggregate requires 'column' and 'agg'.")
        if plan["agg"] not in AGGREGATIONS:
            raise QueryPlanError(f"Unsupported aggregation: {plan['agg']!r}")
        _check_column("column")
        _check_column("group_by")

    elif operation == "top_n":
        if not plan.get("column") or not plan.get("group_by"):
            raise QueryPlanError("top_n requires 'column' and 'group_by'.")
        agg = plan.get("agg", "sum")
        if agg not in AGGREGATIONS:
            raise QueryPlanError(f"Unsupported aggregation: {agg!r}")
        _check_column("column")
        _check_column("group_by")

    elif operation == "count_rows":
        pass  # filters are validated at execution time by apply_filters

    elif operation == "correlation":
        if not plan.get("column_a") or not plan.get("column_b"):
            raise QueryPlanError("correlation requires 'column_a' and 'column_b'.")
        _check_column("column_a")
        _check_column("column_b")

    elif operation == "trend":
        if not plan.get("date_column") or not plan.get("value_column"):
            raise QueryPlanError("trend requires 'date_column' and 'value_column'.")
        _check_column("date_column")
        _check_column("value_column")
        freq = plan.get("freq", "M")
        if freq not in TREND_FREQUENCIES:
            raise QueryPlanError(f"Unsupported trend frequency: {freq!r}")

    elif operation == "unique_values":
        if not plan.get("column"):
            raise QueryPlanError("unique_values requires a 'column'.")
        _check_column("column")


def execute_plan(plan: dict, df: pd.DataFrame) -> dict:
    """Assumes validate_plan() has already passed. Returns a small,
    JSON-serializable dict of real computed numbers — this is what gets
    embedded in the AI's context for the final explanation, never
    generated by the model itself."""
    operation = plan["operation"]

    if operation == "none":
        return {"operation": "none"}

    df = _apply_optional_filters(df, plan.get("filters"))

    if operation == "describe_column":
        return _describe_column(df, plan["column"])
    if operation == "aggregate":
        return _aggregate(df, plan)
    if operation == "top_n":
        return _top_n(df, plan)
    if operation == "count_rows":
        return {"operation": "count_rows", "row_count": int(len(df))}
    if operation == "correlation":
        return _correlation(df, plan["column_a"], plan["column_b"])
    if operation == "trend":
        return _trend(df, plan)
    if operation == "unique_values":
        return _unique_values(df, plan["column"])

    raise QueryPlanError(f"Unhandled operation: {operation!r}")  # pragma: no cover


def _apply_optional_filters(df: pd.DataFrame, filters) -> pd.DataFrame:
    if not filters:
        return df
    try:
        filtered = apply_filters(df, filters)
    except ChartBuildError as exc:
        raise QueryPlanError(str(exc)) from exc
    if filtered.empty:
        raise QueryPlanError("No rows match the requested filters.")
    return filtered


def _describe_column(df, column):
    series = df[column]
    if pd.api.types.is_numeric_dtype(series):
        clean = series.dropna()
        return {
            "operation": "describe_column",
            "column": column,
            "type": "numeric",
            "count": int(clean.count()),
            "mean": _r(clean.mean()),
            "median": _r(clean.median()),
            "min": _r(clean.min()),
            "max": _r(clean.max()),
            "std": _r(clean.std()),
        }
    clean = series.dropna()
    top = clean.value_counts().head(5)
    return {
        "operation": "describe_column",
        "column": column,
        "type": "categorical",
        "count": int(clean.count()),
        "unique_count": int(clean.nunique()),
        "top_values": [{"value": str(i), "count": int(c)} for i, c in top.items()],
    }


def _aggregate(df, plan):
    column, agg, group_by = plan["column"], plan["agg"], plan.get("group_by")
    if group_by:
        grouped = df.groupby(group_by)[column].agg(agg).sort_values(ascending=False).head(MAX_RESULT_ROWS)
        return {
            "operation": "aggregate",
            "column": column,
            "agg": agg,
            "group_by": group_by,
            "results": [{"group": str(i), "value": _r(v)} for i, v in grouped.items()],
        }
    value = df[column].agg(agg)
    return {"operation": "aggregate", "column": column, "agg": agg, "value": _r(value)}


def _top_n(df, plan):
    column, group_by = plan["column"], plan["group_by"]
    agg = plan.get("agg", "sum")
    n = min(int(plan.get("n", 5)), MAX_RESULT_ROWS)
    ascending = bool(plan.get("ascending", False))

    grouped = df.groupby(group_by)[column].agg(agg).sort_values(ascending=ascending).head(n)
    return {
        "operation": "top_n",
        "column": column,
        "group_by": group_by,
        "agg": agg,
        "ascending": ascending,
        "results": [{"group": str(i), "value": _r(v)} for i, v in grouped.items()],
    }


def _correlation(df, column_a, column_b):
    a = pd.to_numeric(df[column_a], errors="coerce")
    b = pd.to_numeric(df[column_b], errors="coerce")
    corr = a.corr(b)
    return {
        "operation": "correlation",
        "column_a": column_a,
        "column_b": column_b,
        "correlation": _r(corr),
    }


def _trend(df, plan):
    date_column, value_column = plan["date_column"], plan["value_column"]
    freq = TREND_FREQUENCIES[plan.get("freq", "M")]
    agg = plan.get("agg", "sum")
    if agg not in AGGREGATIONS:
        agg = "sum"

    sub = df[[date_column, value_column]].copy()
    sub[date_column] = pd.to_datetime(sub[date_column], errors="coerce")
    sub = sub.dropna(subset=[date_column])
    if sub.empty:
        raise QueryPlanError(f"Column '{date_column}' has no valid dates.")

    series = sub.set_index(date_column)[value_column].resample(freq).agg(agg).tail(MAX_TREND_POINTS)
    return {
        "operation": "trend",
        "date_column": date_column,
        "value_column": value_column,
        "freq": plan.get("freq", "M"),
        "points": [{"period": str(idx.date()), "value": _r(v)} for idx, v in series.items()],
    }


def _unique_values(df, column):
    counts = df[column].value_counts().head(20)
    return {
        "operation": "unique_values",
        "column": column,
        "unique_count": int(df[column].nunique()),
        "top_values": [{"value": str(i), "count": int(c)} for i, c in counts.items()],
    }


def _r(value, ndigits=4):
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return None
    return round(float(value), ndigits)
